Implementation of the Covid tracking App
rtonata88/covid-tracer pull request #2
Opened 2022-02-08 21:04 UTC by rtonata88

In this PR I have implemented the following features for the Covid tracking App

- Integrate the Covid API from [Narrativa API](https://covid19tracking.narrativa.com/index_en.html):
- Store the data in a Redux store
- Display the list of countries on the landing page
- Implemented the country details page to show country specific data
- Implemented the back button when user is under a specific country to go back to the list of countries page
- Implemented redux action method testing and country detail snapshop testing

2022-02-08 21:54 UTC, rloterh requested changes
Hi Richard, 

You did extremely great on this project! 👏 👏 
There are however a few issues that you still need to work on to go to the next project but you are almost there! 🚦   🚦  

## Good Points 👍  
- Descriptive Pull Request
- Redux state management properly implemented
- Promise features properly implemented
- Nice UI design
- No linter errors


## Required Changes ♻️
_Kindly check the comments under the review._

<br>
Cheers and Happy coding!👏 💻 🍷

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 4 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-08 21:54 UTC, rloterh commented on README.md
> +## Authors
- [ ] Kindly change the header title _Authors_ to _Author_ on line 34, as this project is done solely. This will make your ReadMe appear more professional.

2022-02-08 21:54 UTC, rloterh commented on src/App.js
> +
- [ ] As specified, kindly implement a **redux filter/ search** functionality so as to enable filtering of countries. The filter/ search field should be displayed on the Homepage.

2022-02-08 21:54 UTC, rloterh commented on src/Components/Countries/CountryDetail.js
> +  /* eslint-disable  max-len */
- [ ] You have **disabled linter check** on your code. Please enable linter check on your code to ensure that your code is robust code and clean.

2022-02-09 16:26 UTC, rtonata88 commented on src/App.js
> +
Good day, Thank you for your review. I don't think the requirements meant we should implement a search functionality. Check out this 1st bullet point under Home page `When the page loads, the webapp shows the list of categories that could be filtered out by some parameter, for example by the category name.`. By virtue of my second page (i.e. Country Details) I have applied a filter based on the country id, to display information from that country only. It's this kind of filter as opposed to a search functionality. Also the provided UI guide has no search input in it. Kindly verify this information before I proceed.

2022-02-09 18:46 UTC, dasileker approved these changes
## **Hi @,** 

## **Congratulations! 🎉 Project Approved ✅**
Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀 
 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-09 19:23 UTC, merged

2022-02-09 19:40 UTC, rloterh commented on src/App.js
> +
hi @rtonata88 
I have explained and we have addressed this issue via slack.